apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nginx
  namespace: default
subjects:
- kind: ServiceAccount
  name: nginx
roleRef:
  kind: Role
  name: nginx
  apiGroup: rbac.authorization.k8s.io
